### ISSUE TITLE
Jellyfin fails transcode for Finamp while Finamp still reports a transcode

### ISSUE THREAD

**Issue by ttrv65ebyng** [jmshrv/finamp#426]
Most of my music library is comprised of ~30MB flac files. In the last week Finamp has accounted for +4GB while the transcode quality is set to 192kbps (in theory, this should do 86.4MB / hour of music), meaning I must have listened to almost 48 hours of music on cellular (not the case). According to the iOS network monitor, my server domain was contacted 135 times over the last week, so I assumed I've played 135 individual songs, each at around 4 minutes. That sets my time listened to 9 hours (this tracks), only about a fifth of the estimate. Additionally, if 135 songs consumed 4GB, each song took about ~30MB, like my lossless flac files. The only conclusion that I can see is my app isn't receiving a transcode for some reason, despite, saying "Streaming Transcode" on the bottom left, while my server dashboard shows "Direct Playing" always. According to the server logs, I get

```Jellyfin.Api.Controllers.DynamicHlsController: cannot serve "/config/data/transcodes/[SOME_RANDOM_TRANSCODE_ID].ts" as it doesn't exist and no transcode is running```

continuously while playing music on Finamp. Is this a known issue?

**Comment by jmshrv** [comment]
That sounds like the transcode is failing. Is there anything interesting in the ffmpeg logs?

**Comment by ttrv65ebyng** [comment]
So the strange thing is that there is no FFMPEG transcode log being created in these instances where the line ```[WRN] [42] Jellyfin.Api.Controllers.DynamicHlsController: cannot serve "/config/data/transcodes/644b09d5ca8e53ecf8a25c1602544d0780.ts" as it doesn't exist and no transcode is running``` shows up on the Jellyfin log. In these instances, the dashboard shows "The source file is entirely compatible with this client, and the session is receiving the file without modifications." There's also no log I can see through the console app on Mac being created on my iOS device referencing my base URL, however, here is the only log that seemed potentially relevant: ```mediaserverd: <SEGPUMP> segPumpVerifyMediaBitrateIsBelowAlternatePeakBitrate: Measured bandwidth is greater than stated in variant: changing required bandwidth from 192000 to 211562```

I tried another song, and it did create a [transcode log](https://github.com/jmshrv/finamp/files/11186008/FFmpeg.Transcode-2023-04-09_13-42-58__f19e7357.log), and the Jellyfin log shows [this](https://github.com/jmshrv/finamp/files/11186017/snippet.log) and the dashboard still says "The source file is entirely compatible with this client, and the session is receiving the file without modifications." The only iOS log referencing my base URL shows the [following](https://github.com/jmshrv/finamp/files/11186032/snippet2.log)

**Comment by jmshrv** [comment]
That is odd. For songs where a transcode log is being made, transcoding should be working properly. Does it repeatedly not work for a specific song? If so, is there anything around it that could indicate transcoding failing?

As for the dashboard message, it's up to the client to send them, which Finamp should be doing.

https://github.com/jmshrv/finamp/blob/aee1efc088ef182dcfd03081074dbd5ccc9a7a44/lib/services/music_player_background_task.dart#L388-L392

**Comment by ttrv65ebyng** [comment]
It is with specific songs, here's an ffprobe of the file of a song that is not creating the transcode log:
```
{
    "format": {
        "filename": "01-13 • So Much (For) Stardust.flac",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "flac",
        "format_long_name": "raw FLAC",
        "start_time": "0.000000",
        "duration": "291.299002",
        "size": "36157748",
        "bit_rate": "993007",
        "probe_score": 100,
        "tags": {
            "ALBUM": "So Much (For) Stardust",
            "album_artist": "Fall Out Boy",
            "ARTIST": "Fall Out Boy",
            "BARCODE": "075679702043",
            "DATE": "2023-03-24",
            "disc": "1",
            "DISCTOTAL": "1",
            "GENRE": "Alternativo;Rock",
            "ISRC": "USAT22220581",
            "ITUNESADVISORY": "0",
            "LANGUAGE": "eng",
            "LENGTH": "291000",
            "PUBLISHER": "Fueled By Ramen",
            "TITLE": "So Much (For) Stardust",
            "track": "13",
            "TRACKTOTAL": "13"
        }
    }
}
```

And here's one that does create a transcode:
```
{
    "format": {
        "filename": "01-01 • DBSAC.flac",
        "nb_streams": 2,
        "nb_programs": 0,
        "format_name": "flac",
        "format_long_name": "raw FLAC",
        "start_time": "0.000000",
        "duration": "147.764036",
        "size": "19509289",
        "bit_rate": "1056240",
        "probe_score": 100,
        "tags": {
            "ALBUM": "DBSAC",
            "album_artist": "The Oozes",
            "ARTIST": "The Oozes",
            "BARCODE": "044003349834",
            "DATE": "2023-02-03",
            "disc": "1",
            "DISCTOTAL": "1",
            "GENRE": "Alternativo;Indie Rock",
            "ISRC": "USZXT2350645",
            "ITUNESADVISORY": "1",
            "LANGUAGE": "eng",
            "LENGTH": "147000",
            "PUBLISHER": "The Oozes",
            "TITLE": "DBSAC",
            "track": "1",
            "TRACKTOTAL": "1"
        }
    }
}
```

But I'm not seeing anything different that could cause this issue here. Is there any other test I could run to see more information about the file? What is the exact command Jellyfin runs to try and transcode the file? I may be able to recreate the error in the console by trying those parameters.

**Comment by ttrv65ebyng** [comment]
As far as why the dashboard is still showing Direct Play in the second instance, I'm not certain, given what you've shared about how Finamp should be telling the server it's a transcode. Jellyfin Server Version: 10.8.9 (ghcr.io/linuxserver/jellyfin in a docker container). Finamp version: 0.6.10.

**Comment by jmshrv** [comment]
Jellyfin gives the ffmpeg command it uses in the transcode logs. In the log that you sent, the command was:

```
ffmpeg -analyzeduration 200M  -i file:"/data/music/The Oozes/DBSAC/01-01 • DBSAC.flac" -map_metadata -1 -map_chapters -1 -threads 0   -acodec libfdk_aac -ab 192000 -ac 2 -vn -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/data/transcodes/74cbbd5e694089bb1e6741b5f00c7410%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/data/transcodes/74cbbd5e694089bb1e6741b5f00c7410.m3u8"
```

**Comment by ttrv65ebyng** [comment]
No issues it seems:
```
root@ade08eeeab1d:/data/music/Fall Out Boy/So Much (For) Stardust# /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M  -i file:"01-13 • So Much (For) Stardust.flac" -map_metadata -1 -map_chapters -1 -threads 0   -acodec libfdk_aac -ab 192000 -ac 2 -vn -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/transcode%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/transcode.m3u8"
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flac, from 'file:01-13 • So Much (For) Stardust.flac':
  Metadata:
    ALBUM           : So Much (For) Stardust
    album_artist    : Fall Out Boy
    ARTIST          : Fall Out Boy
    BARCODE         : 075679702043
    DATE            : 2023-03-24
    disc            : 1
    DISCTOTAL       : 1
    GENRE           : Alternativo;Rock
    ISRC            : USAT22220581
    ITUNESADVISORY  : 0
    LANGUAGE        : eng
    LENGTH          : 291000
    PUBLISHER       : Fueled By Ramen
    TITLE           : So Much (For) Stardust
    track           : 13
    TRACKTOTAL      : 13
  Duration: 00:04:51.30, start: 0.000000, bitrate: 993 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 1200x1200 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[mpegts @ 0x55f41002cf00] frame size not set
Output #0, hls, to '/tmp/transcode.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac, 44100 Hz, stereo, s16, 192 kb/s
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode0.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode1.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode2.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode3.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode4.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode5.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode6.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode7.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode8.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode9.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode10.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode11.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode12.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode13.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode14.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode15.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode16.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode17.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode18.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode19.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode20.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode21.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode22.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode23.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode24.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode25.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode26.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode27.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode28.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode29.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode30.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode31.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode32.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode33.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode34.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode35.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode36.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode37.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode38.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode39.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode40.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode41.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode42.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode43.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode44.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode45.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode46.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode47.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode48.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode49.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode50.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode51.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode52.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode53.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode54.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode55.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode56.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode57.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode58.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode59.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode60.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode61.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode62.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode63.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode64.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode65.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode66.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode67.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode68.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode69.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode70.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode71.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode72.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode73.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode74.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode75.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode76.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode77.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode78.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode79.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode80.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode81.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode82.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode83.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode84.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode85.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode86.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode87.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode88.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode89.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode90.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode91.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode92.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode93.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode94.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode95.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode96.ts' for writing
[hls @ 0x55f40ffa18c0] Opening '/tmp/transcode97.ts' for writing
size=N/A time=00:04:51.27 bitrate=N/A speed=95.3x
video:0kB audio:6829kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Comment by ttrv65ebyng** [comment]
And I've attached a screenshot of the resulting m3u8 stream's info in IINA <img width="489" alt="Screenshot 2023-04-09 at 15 16 30" src="https://user-images.githubusercontent.com/49124157/230792196-dec1b3d8-477e-45dc-a971-89529d12b126.png">

**Comment by jmshrv** [comment]
This is very weird. Could you send your full Finamp logs?

**Comment by ttrv65ebyng** [comment]
Attached! [finamp-logs.txt](https://github.com/jmshrv/finamp/files/11186160/finamp-logs.txt)

**Comment by jmshrv** [comment]
Thanks, I can't see anything wrong there (I should probably add better logs to the audio service lol)

Could you sent your Jellyfin log?

**Comment by ttrv65ebyng** [comment]
Here it is, spanning about 3-4 minutes I tried that song several times, and a few other ones on the album that did seem to create a transcode log: [jellyfin.log](https://github.com/jmshrv/finamp/files/11186236/jellyfin.log)

**Comment by jmshrv** [comment]
Is your mount at `/config` full? Poking through the source code shows that the log message you're getting is done when the transcode job is never made

**Comment by ttrv65ebyng** [comment]
Nope, 800GB available and the mount is rw in docker.

**Comment by jmshrv** [comment]
The fact that it's playing suggests that the transcode is working. I'll do some testing myself on how much data Finamp uses - I have a feeling that I may be spamming progress updates too much on iOS (I added progress updates when I was on Android, which didn't need any rate limiting)

**Comment by ttrv65ebyng** [comment]
I appreciate it! I'll get back to you with some more specifics on data usage in a few days, my data plan renews tomorrow.

**Comment by ttrv65ebyng** [comment]
I just tried playing "So Much (For) Stardust" (my data usage before clicking the song itself way 393KB loading the list of the library). After playing it, my data usage was 10.8MB, suggesting that it IS transcoding, as the original file is 36.2MB, and it may very well be at 192kbps as is set in the settings. (should be 6.984MB used for the song). The reason I say it could be even with that discrepancy, is that some of that data usage is also from it incrementing even after the UI buffer bar has loaded fully (it did about an additional 3MB over the course of of the song after the buffer bar loaded, which just about accounts for the difference). Overall, after listening to the song twice, it used 25.7MB for 9:32 of music, while it should've only consumed 13.78MB (almost half) at 192kbps (+ whatever Finamp uses to communicate with the serve and load artwork). [Here](https://github.com/jmshrv/finamp/files/11192582/finamp-logs.txt) are the logs.

**Comment by jmshrv** [comment]
Thanks! I think I know what's happening here - the increase is due to images being loaded.

Your rip of So Much (For) Stardust has individual images for each song, so Finamp is requesting a "different" image for each song. Loading each of those images (+ any images on the main album screen) is probably pushing it up to 10MB. I've been meaning to "deduplicate" individual images for a while, it should be possible as Jellyfin gives each image a [blurhash](https://blurha.sh/), which we can use to check if images are the same without having to actually load multiple images.

**Comment by jmshrv** [comment]
iOS is also likely pulling down a separate image for each song, which at full size could easily be 1MB+ each.

**Comment by ttrv65ebyng** [comment]
Ah, that make sense! When I tried downloading the album, it did download several images!

**Comment by ttrv65ebyng** [comment]
Any chance there could be a way in future to have metadata/album artwork downloaded locally, and updated automatically when on WiFi (or manually if wanting to update outside of WiFi)? I know it could be several tens of GB for a large library, but my phone definitely has space for that, not so much for all the music itself (my library is currently 400GB if I recall correctly)

**Comment by ttrv65ebyng** [comment]
Although checking the files themselves, the images do seem to be the exact same in all the songs according to my tag editor:
First image showing just that album: <img width="720" alt="Screenshot 2023-04-10 at 14 48 51" src="https://user-images.githubusercontent.com/49124157/230971997-e4a15a46-fe33-4b53-9a84-72811e5e6bd0.png">
And what happens when not all the images match: <img width="710" alt="Screenshot 2023-04-10 at 14 49 00" src="https://user-images.githubusercontent.com/49124157/230972011-84405e60-2a82-4094-9e2f-f9626c752e0d.png">

**Comment by jmshrv** [comment]
Finamp 0.6.11 should never accidentally transcode when expecting direct, and vice versa. Closing this as fixed
