### ISSUE TITLE
Offline mode sorting does not match online mode sorting

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#581]
Jellyfin is one of those pieces of software that sorts "The X" under X instead of T. For instance "The Legend of Zelda" gets sorted with the Ls. In offline mode however I notice that the albums get sorted under T. On top of this jellyfin offers a "Sorting Title" field in the metadata for giving it a title it only sorts by internally but never displays to the user. For instance I could do "Star Wars 1" "Star Wars 2" so that the media would be sorted in order for the series. Offline mode does not appear to respect sorting titles.

Idk if there are any other sorting inconsistencies but it would be nice if it was the same. This isn't a huge issue for me though so if this never gets fixed no big deal. Just wanted to report it.

**Comment by Chaphasilor** [comment]
There is another one, #444

It seems like this should be reasonably easy to fix, since we probably have the sorting title available in offline mode too :)

**Comment by Chaphasilor** [comment]
@puff you fixed this issue as part of your PR, right? :)

**Comment by puff** [comment]
> @puff you fixed this issue as part of your PR, right? :)

Ahh unfortunately not, I only made it case-insensitive which is only part of this issue

**Comment by Chaphasilor** [comment]
Got it, no worries. We can tackle it in a different PR :)

**Comment by jmshrv** [comment]
Fixed in 1706178

**Comment by bravely-beep** [comment]
This issue still occurs if albums have "sort title" metadata. The "sort title" field is respected for sorting in online mode, but not in offline mode.
