### ISSUE TITLE
Playback stops when finamp is not in the foreground 

### ISSUE THREAD

**Issue by csaavedra** [jmshrv/finamp#956]
This started happening to me several days ago. If I switch off the screen or just go to a different app, finamp will stop playback after less than a minute. Going back to the app will resume playback., but sometimes it will just go to the next song in the queue.

I have no battery optimisations enabled for finamp. 

I have tried with Allow Low-Priority Status on Pause enabled and disabled, makes no difference. 

This happens with both offline mode and streaming from my Jellyfin server. 

I'm using a Pixel 7 with Android 15. Version is 0.6.24.

**Comment by jmshrv** [comment]
This may be because I switched `main` back to API 34, since the Play Store now requires it. `redesign` works fine, so maybe there's a dependency update or something that we need to carry over to `main`

**Comment by csaavedra** [comment]
> Also, are you able to pinpoint if this started happening after updating to 0.6.24? That was released about a week ago.

This is very likely. The app store app says finamp was updated 6 days ago. I started experiencing this 4 days ago but I want using the app on the days before that, so that might definitely be it. I'll try going back to an older version.

**Comment by martingagne** [comment]
Hey, I’m encountering the same issue on iOS/iPadOS 18.1 using an iPad Pro M1. When Finamp is not in the foreground, playback stops. This happens both in offline mode and when streaming from my Jellyfin server.

	•	OS Version: iPadOS 18.1
	•	Device: iPad Pro M1
	•	Finamp Version: Latest beta version (used to be just too good—now this bug makes it almost unusable)

I’d be happy to provide logs, but they contain too much sensitive information, like my server name and other details. If there’s a way to anonymize or filter the logs, let me know, and I’ll share them to help resolve this issue.

I hate to complain, but you guys have done a terrific job with this application. In fact, I don’t think it has anything to envy to Apple Music. Thanks for your hard work, and I hope this can be fixed soon!

**Comment by jmshrv** [comment]
Interesting that you're seeing it happen on iOS too. I *very occasionally* have background playback not work (like twice ever) but if it's something that keeps happening that's bad.

As for logs, they're sanitised automatically when you copy/share them. Your server address and token should be censored :)

**Comment by martingagne** [comment]
Attached is the log. I manually censored a bit more since I could still see my fileserver URL and a couple of other things.

This bug is a real bummer because I typically use the app for about 12 hours a day - it’s been such a solid client for Jellyfin until now. Unfortunately, I might need to roll back to the previous version for the time being.

The issue is super consistent: as soon as the iPad or iPhone screen goes dark, or I switch apps, the music stops. Let me know if there’s anything else I can do to help troubleshoot this. You’ve done such an amazing job with this app - I really hope this gets sorted out soon!

[sanitized_log.txt](https://github.com/user-attachments/files/17787815/sanitized_log.txt)

**Comment by bebopjp** [comment]
Same problem here. Playback stops when screen is off after 3-5 minutes. No media controls on notification screen. When I unlock the screen, finamp will start a random track from the album that was previously playing. Started happening in the last week, so likely when the app update occurred.

Pixel 7 pro
Android 15
App version 0.6.24

**Comment by bebopjp** [comment]
Just reproduced and the only errors right before the audio stop are this. No socket errors from other tasks.

```
[MusicPlayerBackgroundTask/SEVERE] 2024-11-17 21:13:07.222372: ClientException with SocketException: Failed host lookup: 'redacted' (OS Error: No address associated with hostname, errno = 7), uri=BASEURL/Sessions/Playing/Progress

null
```

**Comment by Chaphasilor** [comment]
@martingagne thanks for the logs. You said that the previous beta version (0.9.11) workes fine for you, and the bug started appearing with this update?  

The intereting thing in the logs is that while the app is *paused* by the OS multiple times (which is normal and wouldn't normally affect playback), it doesn't seem to have quit completely. In the whole log you shared, which spans almost three days, only one startup is logged.  
That means it's probably not a crash.

The Android users reported playback stopping a *short while after* the app goes into the background, but in your case it's immediately. So it could be a different (perhaps related) issue.

Were you able to downgrade to a previous version?

**Comment by martingagne** [comment]
Yes, I downgraded to the previous version using the app for managing beta
applications on iOS (I believe it’s called TestFlight), and now everything
is back to normal. I can listen to music in the car or at work without
needing to keep the phone and screen turned on all the time. However, in my
case, with the updated version, the music stops immediately as soon as I
press the power button to turn off the screen or switch to another app. I
believe the downgraded version might expire sometime in December.

**Comment by Chaphasilor** [comment]
@jmshrv can you look up which dependency versions were used during your build? Pubspec allowed for the latest versions of everything related to just_audio, but maybe you hadn't pulled them yet?  
I also couldn't find any significant differences in the pubspec and gradle files between main and redesign, aside from some SDK versions (notably dart 2 vs dart 3).

**Comment by jmshrv** [comment]
Updated dependencies, pushing a new build now. Just tested and it looks good :)

**Comment by jmshrv** [comment]
Thanks for letting me know, I'll keep looking into it. For now, I'd recommend you switch to the beta, which isn't affected by this

**Comment by Chaphasilor** [comment]
@shangyuj were those two logs the only logs that were shown? Or did you just leave out the other logs?  
Because it those really are the only logs then the app is definitely getting killed in the background and not just paused.

**Comment by DickChang** [comment]
I've got the same issue. version 0.6.25. pixel 7a. android 15

**Comment by Chaphasilor** [comment]
@DickChang @rawkhopper give the beta a try. You can switch to it through the Play Store at the bottom of [Finamp's store page](https://play.google.com/store/apps/details?id=com.unicornsonlsd.finamp)

**Comment by Thecrafterja** [comment]
I had the same problem on a pixel 9 with Android 15. After switching to the beta provided through google playstore, finamp is working fine again.
The media control is also appearing again 👍 

@Chaphasilor fyi

**Comment by Chaphasilor** [comment]
Got a few questions for you:
1. Playback just *pauses* and you can just hit play again to resume, yes?
2. Could it be that the pausing happens right after you receive a notification? Maybe you could try this out with a friend :)
3. Does the playback progress slider in the media notification keep moving?
4. To those of you that observed skipped tracks, like @bebopjp and @csaavedra, could you check if Finamp the skipped tracks were reported in the Activity tab of your Jellyfin server's admin dashboard?

Combined with your mentions of missing media notifications (also in #977), I'm now suspecting something being wrong with `audio_session` or `audio_service`, which handle audio ducking (reducing volume for notifications, pausing and resuming for calls) and the media notification, respectively.  

PS @demaniak we'll try not to enforce a minimum version, but also don't guarantee compatibility for older (minor) versions. So you should try to upgrade as soon as you can!

**Comment by demaniak** [comment]
> Got a few questions for you:
> 
>     1. Playback just _pauses_ and you can just hit play again to resume, yes?
> 
>     2. Could it be that the pausing happens right after you receive a notification? Maybe you could try this out with a friend :)
> 
>     3. Does the playback progress slider in the media notification keep moving?
> 
>     4. To those of you that observed skipped tracks, like @bebopjp and @csaavedra, could you check if Finamp the skipped tracks were reported in the Activity tab of your Jellyfin server's admin dashboard?
> 
> 
> Combined with your mentions of missing media notifications (also in #977), I'm now suspecting something being wrong with `audio_session` or `audio_service`, which handle audio ducking (reducing volume for notifications, pausing and resuming for calls) and the media notification, respectively.
> 
> PS @demaniak we'll try not to enforce a minimum version, but also don't guarantee compatibility for older (minor) versions. So you should try to upgrade as soon as you can!

1. Not..exactly. It's weird. When in this state, Just hitting play does nothing. Hitting next, does nothing. BUT, hitting the "play random songs from all songs" - that gets music flowing again. For approx 2 songs, then...back to square one. Mostly. Sometimes I get to 3 or 4 songs. 

2. no notifications (yeah I'm a friendless hermit :p )

3. No, for me, the slider is stuck at 0 in these cases

4. Um, just a data point on that from my side - I have in this period also noticed "shortened" tracks - the track would end prematurely and then go on to the next track (or, just stop as explained above).

FWIW, the beta is working very nicely, control widget back in business etc 

Regarding upgrade: yeah... the 10.9+ releases has some wonky memory use issues (in some cases/platforms), but I know I'll have to give it a try again sometime in near future :(

**Comment by Chaphasilor** [comment]
Good news everyone!  
Seems like there are some new permissions required for Android 14+ that are requested in the beta but not on stable:  
https://github.com/ryanheise/just_audio/issues/1363#issuecomment-2562409290

We'll add the missing permissions and push an update ASAP!

**Comment by jmshrv** [comment]
I'll investigate adding those permissions when I get home later today 🫡

**Comment by Chaphasilor** [comment]
@jmshrv I've already committed the changes ^^

**Comment by Chaphasilor** [comment]
Okay, we've pushed an update for this now. Should become available on the Play store in a few hours.

Please try it out and let me know if it's fixed!

**Comment by erahhal** [comment]
Is the latest 0.6.26? Because it's still happening with that version.

**Comment by rik-shaw** [comment]
Sorry new user here so I can't speak to prior issues but both 0.6.25 and 0.6.26 do not have the lockscreen / media playback persistent notification, at least on Lineage 22 / Android 15.

But finamp does NOT stop playing when the screen is off.

Other issue reports on the lockscreen were linked here, so I am not sure if the issue is the same or not.

**Comment by rik-shaw** [comment]
@EmilHeilbo thanks for the testing with the `0.9.x-beta`, I had issues with it recognizing my library correctly. Regarding `0.6.x`, at least for me `0.6.24` is working correctly. It has the lockscreen / persistent media playing notification work correctly (`0.6.25` AND `0.6.26` both tested and did not work.

I'll jump to the beta again and re-test.

BTW Lineage4MicroG 22 (A15) on a Pixel 3a XL bonito

**Comment by Chaphasilor** [comment]
Hey, can anyone who had this issue please test if it's still happening with the version below? I think I found a proper fix now, but want to make sure.

https://gofile.io/d/sgbvDz

(This version will install alongside the regular version of Finamp without interference, but you will have to log into it again separately)

**Comment by erahhal** [comment]
Can confirm that it no longer stops playing, thank you!

**Comment by christophehenry** [comment]
Confirms here too. The player keeps playing as intended.

**Comment by erahhal** [comment]
Is 0.6.26 released 5 days ago on Fdroid supposed to have the fix? Because it is still broken.

**Comment by erahhal** [comment]
By the way, VLC has the same issue, even recent dev builds. I'm surprised this isn't more of a big deal in the android community.

**Comment by Chaphasilor** [comment]
@erahhal no, F-Droid is lagging behind. The most recent version is 0.6.27, and *that* should fix the issue. Just wait a bit longer for F-Droid's automated build service to pick it up...

**Comment by csaavedra** [comment]
This seems fixed for me, I have been using 0.6.27 for several days and it works without pausing playback when the phone is dimmed.

**Comment by Siress** [comment]
Pixel 8 Android 15 finamp 0.6.27

Still happening

**Comment by Chaphasilor** [comment]
@Siress on 0.6.27?

Can you check the battery usage permissions for Finamp please?

**Comment by Siress** [comment]
Background usage allowed.

**Comment by Chaphasilor** [comment]
@Siress so, did changing the setting help?

**Comment by Siress** [comment]
Unfotunately not.

**Comment by Chaphasilor** [comment]
Hmm. In that case I can only recommend that you switch to the beta for now @Siress, that should be more reliable.

**Comment by f8ith** [comment]
Finamp on beta in the Play Store still does not request permissions. Might have to do with the fact that I switched to the beta after having stable installed beforehand?

Android 14, Pixel 7.

**Comment by csaavedra** [comment]
This has been working for me reliably since it was allegedly fixed in 0.6.27, so from my side this can be closed. Since there are others that seem to still have the issue I will not close it myself, but I am unsubscribing as I have nothing to add here.

**Comment by mjevange** [comment]
I think I found the residual cause here. On Android 12+, a brief audio-focus loss while Finamp is backgrounded (a notification, alarm, nav prompt, or a few seconds of audio from another app) pauses playback and drops the audio service out of the foreground. When focus returns, Android blocks restarting the foreground service from the background (`FGS: Disallowed` / `mAllowStartForeground false`), so playback stays dead until you reopen the app.

On a Pixel 9 Pro / Android 16 / 0.9.23-beta, turning **Enter Low-Priority State on Pause** OFF fixes it — confirmed with adb logcat (the denial disappears and playback resumes right after the interruption). Some older 0.6.x reports said this toggle made no difference, but on `redesign` it does.

Opened #1643 proposing to default that setting off. Would appreciate thoughts/testing from anyone still affected.
