### ISSUE TITLE
Some 2 digit and all 3 digit track numbers are broken

### ISSUE THREAD

**Issue by felix920506** [jmshrv/finamp#960]
Some 2 digit track numbers and all 3 digit track numbers are shown in 2 lines. See the attached screenshots for how they are displayed.

Screenshots are taken on my iPhone 13 mini, but the 3 digit ones are also broken on my ChromeOS tablet running the Android version.

This is using the beta version from TestFlight / Google play 

![image](https://github.com/user-attachments/assets/9bc57d33-9324-4edb-8a3a-aba155c07cad)

![image](https://github.com/user-attachments/assets/304f3073-372a-4ab5-9c13-7897fb5688bb)

**Comment by Chaphasilor** [comment]
Yeah this is definitely a side effect from the redesign of the list tiles in the latest beta version. Thanks for reporting it.

I wasn't even aware there are 3-digit index numbers (silly me), and I'm not sure I'll like the fix for it. But I'll definitely fix it for the next update! Not sure when that will drop.

**Comment by Chaphasilor** [comment]
Should be fixed in the next beta update!  
For longer (wider) track numbers the title might get shifted to the right. That isn't ideal and might look weird in some cases, but I prefer it over allocating more space for the track numbers that isn't used in the majority of cases.

**Comment by Titaniumtown** [comment]
I can still reproduce this. Also noticed this in the same album @felix920506 haha!

**Comment by Chaphasilor** [comment]
@Titaniumtown is this still happening? I'm not sure when the fix for this was released...

**Comment by felix920506** [comment]
it's fixed in latest TestFlight build

**Comment by Titaniumtown** [comment]
@Chaphasilor it works now, the issue can be closed
